### PR TITLE
[BACKLOG-15101] Rename package for correct i18n

### PR DESCRIPTION
**Pull request by AlexanderBuloichik**

### CODE REVIEW

**Comment by mdamour1976** [comment]
@AlexanderBuloichik @bmorrise So this was a result of mavenization?  I am wondering why the fix wasn't to just move the location of the bundle:  https://github.com/pentaho/pentaho-vertica-bulkloader/tree/master/core/src/main/resources/org/pentaho/di/verticabulkloader/messages

**Comment by AlexanderBuloichik** [comment]
@mdamour1976 yes, probably it happens after mavanization.
But idea is simple - package of code and messages should be the same. I could rename messages bundle, of course, but looks like "verticabulkloader" is more correctly than "verticabulkload".
But I can change message's package instead of code's package, of course.

**Comment by mdamour1976** [comment]
@AlexanderBuloichik ok.  Let's keep this as simple as possible - and introduce zero risk - compared to what is probably very low risk of changing package.  I doubt anyone is referencing it in code, but they could, in 3rd party/customer solutions for example.

**Comment by AlexanderBuloichik** [comment]
@mdamour1976 done, ready to merge

**Pull request merged**
