### PR TITLE
[BACKLOG-14008] - Mavenize pentaho-vertica-bulkloader

### PR DESCRIPTION
**Pull request by ViswesvarSekar**
@pentaho/2-1b

### CODE REVIEW

**Comment by tmcsantos** [comment]
You need to add the license configuration on the root pom as listed here https://github.com/pentaho/maven-parent-poms-ee/wiki/Handling-Software-Licenses-in-a-Maven-Project#lgpl-21

**Comment by hbfernandes** [comment]
oi

**Comment by hbfernandes** [comment]
You need to add the license configuration on the root pom as listed here https://github.com/pentaho/maven-parent-poms-ee/wiki/Handling-Software-Licenses-in-a-Maven-Project#lgpl-21

**Comment by ViswesvarSekar** [comment]
@hbfernandes updated , please review

**Pull request closed without merging**
